name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
    default: "main"
  sonarcloud_token:
       description: "Token For Sonarcloud"
       required: true
  sonarcloud_host_url:     
       description: "Sonarcloud Host URL"
       required: true
  sonarcloud_organization:
       description: "Organization Name on Sonarcloud "
       required: true
  sonarcloud_sources:
       description: "source folder"
       required: true   
  sonarcloud_projectKey:
       description: "Sonar project key"
       required: true
  sonarcloud_coverage_jacoco_xmlReportPaths:
       description: "Jacoco reports path"
       required: true
  sonarcloud_java_binaries:
       description: "Java binaries folder"
       required: true         
  sonarcloud_tests:
       description: "Java test folder"
       required: true                
runs:
  using: "composite" 
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Maven Build
      if: inputs.branch_name == 'main' || inputs.branch_name == 'master'
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dmaven.build.cache.enabled=false \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -PcodeQuality

    - name: Maven Build -- Feature Branch
      if: inputs.branch_name != 'main' && inputs.branch_name != 'master'
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=true \
            -PcodeQuality
            
    - name: SonarCloud Build and analyze
      shell: bash 
      env:
          SONAR_TOKEN: ${{ sonarcloud_token }}
          SONAR_HOST_URL: ${{ sonarcloud_host_url }}
          SONAR_ORGANIZATION: ${{ 'ikmdev' }}  
      run: | 
          ./mvnw verify sonar:sonar \
            --batch-mode \
            -Dsonar.organization=${{ sonarcloud_organization }} \
            -Dsonar.sources=${{ sonarcloud_sources }} \
            -Dsonar.projectKey=${{ sonarcloud_projectKey }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=${{ sonarcloud_coverage_jacoco_xmlReportPaths }} \
            -Dsonar.java.binaries=${{ sonarcloud_java_binaries }} \
            -Dsonar.tests=${{ sonarcloud_tests }}

